name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.ts"
      - "**/*.ts"
      - "**/*.vue"

env:
  TZ: Asia/Tokyo

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          echo "Hello World"
